### ISSUE TITLE
Webhook Create requests fail to service target without domain root handler

### ISSUE THREAD

**Issue by BrianJVarley** [zendesk/sunshine-conversations-api-spec#3]
Adding a webhook to a service that doesn't contain a domain root GET handler results in smooch API failing to add webhook. Smooch dashboard give a generic 400 error but doesn't explain further the reason for the webhook create failure.

How to recreate:

Deploy a smooch node service on an example domain `test-sandbox.com/messages` without 
a default `/` route handler.

Try to add a webhook which will fail because the service doesn't expose a default domain root handler.

Expected outcome:

Smooch API should add a sub error message in network request response detailing that 
target service doesn't contain a domain root route handler.

Smooch API docs should call out that adding a service without a domain root route handler 
will cause webhook CREATE request to fail.

Smooch API docs link: 
https://docs.smooch.io/rest/?shell#manage-webhooks

Reference Client:
https://github.com/smooch/smooch-api-quickstart-example

**Comment by DataWearsAHood** [comment]
Thanks for pointing this out! 
I've started a PR to copy this note over from v1 guide to v2.
