### ISSUE TITLE
Error parsing conversation:message

### ISSUE THREAD

**Issue by amtyurin** [zendesk/sunshine-conversations-api-spec#5]
I use classes generated by openapi-generator and trying to parse incoming webhook message "conversation"message", but get the following error:
java.lang.IllegalArgumentException: Could not resolve type id 'text' as a subtype of `com.mycompany.services.sunshine.api.rest.models.Content`: Class `com.mycompany.services.sunshine.api.rest.models.TextMessage` not subtype of `com.mycompany.services.sunshine.api.rest.models.Content`
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.mycompany.services.sunshine.api.rest.models.ConversationMessageEvent["payload"]->com.mycompany.services.sunshine.api.rest.models.ConversationMessageEventAllOfPayload["message"]->com.mycompany.services.sunshine.api.rest.models.MessageWebhook["content"])

looks like schema is not up to date and does not correspond to the event data.

**Comment by DataWearsAHood** [comment]
Hello @amtyurin 

I've checked with the Dev team and they've confirmed that the included classes are intended to be used to build API request payloads, and parse the response payloads.

Using the same classes to parse webhook events is not an intended, or supported use-case - you'll have to build your own class[es].
